changelog:
  categories:
    - title: Features
      labels:
        - '*'
      exclude:
        labels:
          - fix
          - breaking-change
          - dependencies
          - bot
    - title: Bug Fixes
      labels:
        - fix
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: Dependencies
      labels:
        - dependencies
