[[spring-cloud-discovery-support]]
= Client Discovery =

Spring Boot Admin Server can use Spring Clouds `DiscoveryClient` to discover applications.
The advantage is that the clients don't have to include the `spring-boot-admin-starter-client`.
You just have to add a `DiscoveryClient` implementation to your admin server - everything else is done by AutoConfiguration.

[[spring-cloud-discovery-static-config]]
== Static Configuration ==

Spring Cloud provides a `SimpleDiscoveryClient`.
It allows you to specify client applications via static configuration:

[source,xml]
.pom.xml
----
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter</artifactId>
</dependency>
----

[source,yml]
.application.yml
----
spring:
  cloud:
    discovery:
      client:
        simple:
          instances:
            test:
              - uri: http://instance1.intern:8080
                metadata:
                  management.context-path: /actuator
              - uri: http://instance2.intern:8080
                metadata:
                  management.context-path: /actuator
----

== Dynamic Configuration ==

Spring Boot Admin supports all other implementations of Spring Cloud's `DiscoveryClient` (https://docs.spring.io/spring-cloud-netflix/docs/current/reference/html/#service-discovery-eureka-clients/[Eureka], https://docs.spring.io/spring-cloud-zookeeper/docs/current/reference/html/#spring-cloud-zookeeper-discovery[Zookeeper], https://docs.spring.io/spring-cloud-consul/docs/current/reference/html/#spring-cloud-consul-discovery[Consul], https://docs.spring.io/spring-cloud-kubernetes/docs/current/reference/html/#discoveryclient-for-kubernetes[Kubernetes], ...).
You need to add it to the Spring Boot Admin Server and configure it properly.


[[discover-clients-via-spring-cloud-discovery]]
=== Example using Eureka

If you already use Spring Cloud Discovery for your applications you don't need the SBA Client.
Just add a DiscoveryClient to Spring Boot Admin Server, the rest is done by our AutoConfiguration.

The following steps uses Eureka, but other Spring Cloud Discovery implementations are supported as well.
There are examples using {github-src}/spring-boot-admin-samples/spring-boot-admin-sample-consul/[Consul] and https://github.com/codecentric/spring-boot-admin/tree/master/spring-boot-admin-samples/spring-boot-admin-sample-zookeeper/[Zookeeper].

Also, have a look at the http://projects.spring.io/spring-cloud/spring-cloud.html[Spring Cloud documentation].

. Add spring-cloud-starter-eureka to your dependencies:
+
[source,xml]
.pom.xml
----
include::{samples-dir}/spring-boot-admin-sample-eureka/pom.xml[tags=dependency-eureka,indent=0]
----

. Enable discovery by adding `@EnableDiscoveryClient` to your configuration:
+
[source,java]
----
@Configuration
@EnableAutoConfiguration
@EnableDiscoveryClient
@EnableScheduling
@EnableAdminServer
public class SpringBootAdminApplication {
    public static void main(String[] args) {
        SpringApplication.run(SpringBootAdminApplication.class, args);
    }
}
----

. Tell the Eureka client where to find the service registry:
+
[source,yml]
.application.yml
----
include::{samples-dir}/spring-boot-admin-sample-eureka/src/main/resources/application.yml[tags=configuration-eureka]
----

TIP: You can include the Spring Boot Admin Server to your Eureka server.
Setup everything as described above and set `spring.boot.admin.context-path` to something different than `"/"` so that the Spring Boot Admin Server UI won't clash with Eureka's one.



== Converting ServiceInstances ==

The information from the service registry are converted by the `ServiceInstanceConverter`.
Spring Boot Admin ships with a default and Eureka converter implementation.
The correct one is selected by AutoConfiguration.

TIP: You can modify how the information from the registry is used to register the application by using SBA Server configuration options and instance metadata.
The values from the metadata takes precedence over the server config.
If the plenty of options don't fit your needs you can provide your own `ServiceInstanceConverter`.

NOTE: When using Eureka, the `healthCheckUrl` known to Eureka is used for health-checking, which can be set on your client using `eureka.instance.healthCheckUrl`.

.Instance metadata options
[cols="2,1"]
|===
| Key | Default value

| `user.name`, `user.password`
|
2+| Credentials being used to access the endpoints.

| `management.scheme`
|
2+| The scheme is substituted in the service URL and will be used for accessing the actuator endpoints.

| `management.address`
|
2+| The address is substituted in the service URL and will be used for accessing the actuator endpoints.

| `management.port`
|
2+| The port is substituted in the service URL and will be used for accessing the actuator endpoints.

| `management.context-path`
| `${spring.boot.admin.discovery.converter.management-context-path}`
2+| The path is appended to the service URL and will be used for accessing the actuator endpoints.

| `health.path`
| `${spring.boot.admin.discovery.converter.health-endpoint}`
2+| The path is appended to the service URL and will be used for the health-checking. Ignored by the `EurekaServiceInstanceConverter`.
|===

.Discovery configuration options
[cols="2,1"]
|===
| Property name | Default value

| `spring.boot.admin.discovery.enabled`
| `true`
2+| Enables the DiscoveryClient-support for the admin server.

| `spring.boot.admin.discovery.converter.management-context-path`
| `/actuator`
2+| Will be appended to the service-url of the discovered service when the management-url is converted by the `DefaultServiceInstanceConverter`.

| `spring.boot.admin.discovery.converter.health-endpoint-path`
| `"health"`
2+| Will be appended to the management-url of the discovered service when the health-url is converted by the `DefaultServiceInstanceConverter`.

| `spring.boot.admin.discovery.ignored-services`
|
2+| This services will be ignored when using discovery and not registered as application. Supports simple patterns (e.g. +++"foo*"+++, +++"*bar"+++, +++"foo*bar*"+++).

| `spring.boot.admin.discovery.services`
| `"*"`
2+| This services will be included when using discovery and registered as application. Supports simple patterns (e.g. +++"foo*"+++, +++"*bar"+++, +++"foo*bar*"+++).

| `spring.boot.admin.discovery.ignored-instances-metadata`
|
2+| Instances of services will be ignored if they contain at least one metadata item that matches this list. (e.g. +++"discoverable=false"+++)

| `spring.boot.admin.discovery.instances-metadata`
|
2+| Instances of services will be included if they contain at least one metadata item that matches this list. (e.g. +++"discoverable=true"+++)
|===

== CloudFoundry ==

If you are deploying your applications to CloudFoundry then `vcap.application.application_id` and `vcap.application.instance_index` *_must_* be added to the metadata for proper registration of applications with Spring Boot Admin Server.
Here is a sample configuration for Eureka:

[source,yml]
.application.yml
----
eureka:
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80
    metadata-map:
      applicationId: ${vcap.application.application_id}
      instanceId: ${vcap.application.instance_index}
----
