spring:
  application:
    name: zookeeper-example
  cloud:
    config:
      enabled: false
    zookeeper:
      connect-string: localhost:2181
      discovery:
        metadata:
          management.context-path: /foo
          health.path: /ping
          user.name: user
          user.password: password
  profiles:
    active:
      - secure

management:
  endpoints:
    web:
      exposure:
        include: "*"
      path-mapping:
        health: /ping
      base-path: /foo
  endpoint:
    health:
      show-details: ALWAYS

---
spring:
  profiles: insecure

---
spring:
  profiles: secure
  security:
    user:
      name: "user"
      password: "password"

