spring:
  application:
    name: zookeeper-example
  cloud:
    config:
      enabled: false
    zookeeper:
      connect-string: localhost:2181
      discovery:
        metadata:
          management.context-path: /foo
          health.path: /ping

management.context-path: /foo
endpoints.health.path: /ping

