spring:
  application:
    name: zookeeper-example
  cloud:
    config:
      enabled: false
    zookeeper:
      connect-string: localhost:2181
      discovery:
        metadata:
          management.context-path: /zk-admin
          health.path: /health

management.context-path: /zk-admin
