spring:
  application:
    name: spring-boot-admin-sample-oauth2-client

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://YOUR_ISSUER_URL

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  boot:
    admin:
      client:
        url: http://localhost:8080
