[[monitoring-spring-boot-1.5.x]]
== Monitoring Spring Boot 1.5.x ==

It is possible to monitor Spring Boot 1.5.x applications with Spring Boot Admin 2.x. The old Spring Boot Admin Client is
able to register at a newer server. Since the API has slight changes, you need to set the following property on old clients:

. Reconfigure the api path for Spring Boot Admin Client 1.5.x:
+
[source,yml]
.application.yml
----
spring.boot.admin.api-path: instances
----

As some of the actuator endpoints changed with the Spring Boot 2 release not all options might be available
(e.g. `/metrics` endpoint); for some of the endpoints we provide legacy converters.

== Changes with 2.x ==

* Added stable automatic-module-name to all jars

=== UI
* Rewritten ui using vue.js
* Integrated ui-login module into the main ui module
* Removed ui-activiti module, as it was only used rarely
* Removed Hystrix-Dashboard integration (subject to change)
* Added support for the session endpoint
* Added display of the (sanitized) metadata
* Added option to reset loglevels
* Added wallboard view

=== Backend
* Moved all classes to the `spring.boot.admin.server` package
* Spring cloud related extenstions moved to `spring-boot-admin-server-cloud`.
* Redesigned backend using event sourcing principles
* Added concept of applications (consisting of 1 to n instances)
* Moved endpoint detection to the backend by querying the `/actuator`-index or by probing via OPTIONS request
* Replaced Zuul with a custom proxy using the WebClient
* Removed dependency on spring-cloud-starter
* Added `CompositeHttpHeadersProvider` to support multiple `HttpHeadersProviders` at the same time
* Added `InstanceExchangeFilterFunction`s which allows to intercept/modify the requests to the monitored instances
* Added out-of-the-box support for CloudFoundry
* Added support for Spring Boot 1.5.x actuator endpoints using `LegacyEndpointConverters`
* Update `OpsGenieNotifier` to api v2
* Rewritten the `MailNotifier` to use Thymeleaf templates

=== Client
* Moved all properties to `spring.boot.admin.client.*` and `spring.boot.admin.client.instance.*`
* Moved all classes to the `spring.boot.admin.client` package
* Added support webflux applications
* Added out-of-the-box support for CloudFoundry
