=== UI Modules ===

Additional to the core UI there are following modules which can be included by adding the jar-file to the classpath:

 - spring-boot-admin-server-ui-activiti
 - spring-boot-admin-server-ui-hystrix
 - spring-boot-admin-server-ui-turbine

==== Hystrix UI Module ====

The Hystrix module uses the hystrix-dashboard to display the metrics from Hystrix streams.

. Add the ui module to your classpath:
+
[source,xml,subs="verbatim,attributes"]
.pom.xml
----
<dependency>
    <groupId>de.codecentric</groupId>
    <artifactId>spring-boot-admin-server-ui-hystrix</artifactId>
    <version>{project-version}</version>
</dependency>
----

. Add the `/hystrix.stream` to the proxified endpoints:
+
[source,yml]
.application.yml
----
include::{samples-dir}/spring-boot-admin-sample-eureka/src/main/resources/application.yml[tags=configuration-ui-hystrix]
----

==== Turbine UI Module ====

The Turbine module uses the hystrix-dashboard to display the metrics from a Turbine stream. The UI module does not configure Turbine for you. Either you run Turbine as a separate application or integrate it into your Spring Boot Admin application. Please see http://cloud.spring.io/spring-cloud-static/{spring-cloud-version}/#_turbine[Spring Cloud Reference] on setting up Turbine.

. Add the ui module to your classpath:
+
[source,xml,subs="verbatim,attributes"]
.pom.xml
----
<dependency>
    <groupId>de.codecentric</groupId>
    <artifactId>spring-boot-admin-server-ui-turbine</artifactId>
    <version>{project-version}</version>
</dependency>
----

. Configure the Turbine server and clusters
+
[source,yml]
.application.yml
----
include::{samples-dir}/spring-boot-admin-sample-eureka/src/main/resources/application.yml[tags=configuration-ui-turbine]
----
<1> Configures the service with id `turbine` as Turbine server. URLs are also allowed.

.Turbine UI Module configuration options
|===
| Property name |Description |Default value

| spring.boot.admin.turbine.enabled
| Enable the Spring Boot Admin backend configuration for Turbine.
| `true`

| spring.boot.admin.turbine.location
| ServiceId or URL (without the `/turbine.stream` path) for the Turbine server. Must be reachable from admin server.
| `"turbine"`

| spring.boot.admin.turbine.clusters
| List of available Turbine clusters.
| `"default"`

|
|===

==== Activiti UI Module ====

The Activiti module shows information from the `/activti` endpoint.

. Add the ui module to your classpath:
+
[source,xml,subs="verbatim,attributes"]
.pom.xml
----
<dependency>
    <groupId>de.codecentric</groupId>
    <artifactId>spring-boot-admin-server-ui-activiti</artifactId>
    <version>{project-version}</version>
</dependency>
----

. Add the `/activiti` to the proxified endpoints:
+
[source,yml]
.application.yml
----
spring.boot.admin.routes.endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,activiti
----

==== Login UI Module ====

The Login module just provides you a login page and a logout button.

. Add the ui module to your classpath:
+
[source,xml,subs="verbatim,attributes"]
.pom.xml
----
<dependency>
    <groupId>de.codecentric</groupId>
    <artifactId>spring-boot-admin-server-ui-login</artifactId>
    <version>{project-version}</version>
</dependency>
----
