name: 📖 Deploy Documentation

on:
  workflow_dispatch:
    inputs:
      releaseversion:
        description: 'Release version'
        required: true
        default: '3.0.0'
      copyDocsToCurrent:
        description: "Should the docs be published at https://docs.spring-boot-admin.com? Otherwise they will be accessible by version number only."
        required: true
        type: boolean
        default: false
env:
  VERSION: ${{ github.event.inputs.releaseversion }}

jobs:
  deploy-documentation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          ref: refs/tags/${{ github.event.inputs.releaseversion }}

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Cache node modules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Set projects Maven version to GitHub Action GUI set version
        run: ./mvnw versions:set "-DnewVersion=${{ github.event.inputs.releaseversion }}" --no-transfer-progress

      - name: Build with Maven
        run: ./mvnw -B --no-transfer-progress install -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy documentation to GitHub Pages for version ${{ github.event.inputs.releaseversion }}
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          branch: gh-pages
          folder: spring-boot-admin-docs/target/generated-docs/build
          target-folder: ${{ github.event.inputs.releaseversion }}
          clean: true

      - name: Deploy redirect for /current to /${{ github.event.inputs.releaseversion }}
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        if: github.event.inputs.copyDocsToCurrent == 'true'
        with:
          branch: gh-pages
          folder: spring-boot-admin-docs/target/generated-docs/build/current
          target-folder: /current
          clean: true

      - name: Deploy deeplink redirect for /current/* to /${{ github.event.inputs.releaseversion }}/*
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        if: github.event.inputs.copyDocsToCurrent == 'true'
        with:
          branch: gh-pages
          folder: spring-boot-admin-docs/target/generated-docs/build/current
          target-folder: /
          clean: false
